import { readFile } from 'node:fs/promises';

import { expect, test } from '@playwright/test';

import { signIn, write, zipText } from './helpers';

test('a user saves a token and exports a page tree in PDF and Word', async ({ page }) => {
  await signIn(page);
  // Start without a token, whatever the other tests left.
  await page.request.delete('/api/preferences/pat', { headers: write });
  await page.reload();
  await expect(page.getByRole('alert')).toContainText('No Confluence personal access token is configured');

  // The token is checked against Confluence before it is saved.
  await page.getByRole('link', { name: 'Preferences', exact: true }).click();
  await page.getByLabel('Token', { exact: true }).fill('not-a-token');
  await page.getByRole('button', { name: 'Verify and save' }).click();
  await expect(page.getByText(/invalid or expired/i)).toBeVisible();
  await page.getByLabel('Token', { exact: true }).fill('dev-pat');
  await page.getByRole('button', { name: 'Verify and save' }).click();
  await expect(page.getByText('Token valid for “John Doe” and saved.')).toBeVisible();

  for (const format of ['PDF', 'Word (.docx)']) {
    await page
      .getByRole('navigation', { name: 'Main navigation' })
      .getByRole('link', { name: 'New export' })
      .click();
    await page.getByLabel(/Search for a page/).fill('Rendering');
    await page.getByRole('button', { name: /Rendering reference/ }).click();
    // The tree preview loads the children from Confluence.
    await expect(page.getByRole('tree', { name: 'Exported page tree' })).toContainText('Structure');
    await page.getByRole('radio', { name: format }).check();
    await page.getByLabel('Classification').selectOption('Confidential');
    await page.getByRole('button', { name: 'Start export' }).click();
    await expect(page.getByRole('heading', { name: 'My exports' })).toBeVisible();
  }

  // Both documents are generated by the worker, then offered for download.
  const downloads = page
    .getByRole('row')
    .filter({ hasText: 'Rendering reference' })
    .getByRole('link', { name: /Download/ });
  await expect(downloads).toHaveCount(2, { timeout: 180_000 });

  const files: Record<string, Buffer> = {};
  for (let i = 0; i < 2; i++) {
    const [download] = await Promise.all([page.waitForEvent('download'), downloads.nth(i).click()]);
    files[download.suggestedFilename()] = await readFile(await download.path());
  }
  const pdf = Object.entries(files).find(([name]) => name.endsWith('.pdf'))?.[1];
  const docx = Object.entries(files).find(([name]) => name.endsWith('.docx'))?.[1];
  expect(pdf?.subarray(0, 5).toString()).toBe('%PDF-');
  expect(docx?.subarray(0, 2).toString()).toBe('PK');

  // The Word document holds the whole tree, marked with the classification
  // and the requester.
  const body = zipText(docx!, /^word\/document\.xml$/);
  for (const title of ['Rendering reference', 'Structure', 'Tables', 'Hostile content', 'Depth 6']) {
    expect(body).toContain(title);
  }
  expect(body).not.toContain('evil.example');
  const footers = zipText(docx!, /^word\/.*footer.*\.xml$/);
  expect(footers).toContain('Dev User');
  expect(footers).toContain('Confidential');

  // Finished exports are announced in the inbox.
  await expect(page.getByRole('link', { name: /Notifications, \d+ unread/ })).toBeVisible({
    timeout: 45_000,
  });
  await page.getByRole('link', { name: /Notifications/ }).click();
  await expect(page.getByText('Your export of “Rendering reference” is ready').first()).toBeVisible();
});
