// Package storage persists generated documents. The BlobStore interface keeps
// the rest of the code independent from the backend (local disk today, an
// object store such as S3 tomorrow).
package storage

import (
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
)

var ErrInvalidKey = errors.New("storage: invalid key")

type BlobStore interface {
	Put(ctx context.Context, key string, r io.Reader) (int64, error)
	Open(ctx context.Context, key string) (io.ReadSeekCloser, error)
	// Delete removes the blob; deleting a missing blob is not an error.
	Delete(ctx context.Context, key string) error
}

// keys are generated by the application ("<uuid>.<ext>"); anything else is
// rejected to rule out path traversal.
var keyPattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$`)

type Local struct {
	dir string
}

func NewLocal(dir string) (*Local, error) {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return nil, fmt.Errorf("storage: creating %s: %w", dir, err)
	}
	return &Local{dir: dir}, nil
}

func (l *Local) path(key string) (string, error) {
	if !keyPattern.MatchString(key) || key == "." || key == ".." {
		return "", ErrInvalidKey
	}
	return filepath.Join(l.dir, key), nil
}

// Put writes atomically: readers never observe a partially written file.
func (l *Local) Put(_ context.Context, key string, r io.Reader) (int64, error) {
	p, err := l.path(key)
	if err != nil {
		return 0, err
	}
	tmp, err := os.CreateTemp(l.dir, ".upload-*")
	if err != nil {
		return 0, err
	}
	defer os.Remove(tmp.Name()) // no-op after a successful rename
	n, err := io.Copy(tmp, r)
	if err != nil {
		_ = tmp.Close()
		return 0, err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return 0, err
	}
	if err := tmp.Close(); err != nil {
		return 0, err
	}
	if err := os.Rename(tmp.Name(), p); err != nil {
		return 0, err
	}
	return n, nil
}

func (l *Local) Open(_ context.Context, key string) (io.ReadSeekCloser, error) {
	p, err := l.path(key)
	if err != nil {
		return nil, err
	}
	return os.Open(p) //nolint:gosec // G304: key validated against keyPattern in path()
}

func (l *Local) Delete(_ context.Context, key string) error {
	p, err := l.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	return nil
}
