apiVersion: v1
kind: Service
metadata:
  name: {{ include "confluence-to-doc.fullname" . }}
  labels: {{- include "confluence-to-doc.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "confluence-to-doc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
